package com.chen.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	/**
	 * 用户id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户名
	 */
	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}
	
	/**
	 * 用户名
	 */
	public java.lang.String getUserName() {
		return getStr("userName");
	}

	/**
	 * 用户密码
	 */
	public void setPassWord(java.lang.String passWord) {
		set("passWord", passWord);
	}
	
	/**
	 * 用户密码
	 */
	public java.lang.String getPassWord() {
		return getStr("passWord");
	}

	/**
	 * 用户角色管理，1是管理员，2是普通用户
	 */
	public void setRole(java.lang.Integer role) {
		set("role", role);
	}
	
	/**
	 * 用户角色管理，1是管理员，2是普通用户
	 */
	public java.lang.Integer getRole() {
		return getInt("role");
	}

}
