package com.chen.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBorrow<M extends BaseBorrow<M>> extends Model<M> implements IBean {

	/**
	 * id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 书本id
	 */
	public void setBookId(java.lang.Integer bookId) {
		set("book_id", bookId);
	}
	
	/**
	 * 书本id
	 */
	public java.lang.Integer getBookId() {
		return getInt("book_id");
	}

}
